// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class BareMetalSolutionLogging: BareMetalSolutionStub {
    let inner: any BareMetalSolutionStub
    let logger: Logger

    public init(_ inner: any BareMetalSolutionStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-baremetalsolution-v2"
      logger[metadataKey: "gcp.client.service"] = "baremetalsolution"
      logger[metadataKey: "gcp.experimental.swift.client"] = "BareMetalSolution"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInstances",
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Instance {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInstance",
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateInstance",
        action: {
          (r: UpdateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func renameInstance(
      request: RenameInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Instance {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameInstance",
        action: {
          (r: RenameInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Instance
          in
          return try await self.inner.renameInstance(request: r, options: o)
        })
    }

    public func resetInstance(
      request: ResetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resetInstance",
        action: {
          (r: ResetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resetInstance(request: r, options: o)
        })
    }

    public func startInstance(
      request: StartInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startInstance",
        action: {
          (r: StartInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startInstance(request: r, options: o)
        })
    }

    public func stopInstance(
      request: StopInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopInstance",
        action: {
          (r: StopInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopInstance(request: r, options: o)
        })
    }

    public func enableInteractiveSerialConsole(
      request: EnableInteractiveSerialConsoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "enableInteractiveSerialConsole",
        action: {
          (r: EnableInteractiveSerialConsoleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.enableInteractiveSerialConsole(request: r, options: o)
        })
    }

    public func disableInteractiveSerialConsole(
      request: DisableInteractiveSerialConsoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "disableInteractiveSerialConsole",
        action: {
          (r: DisableInteractiveSerialConsoleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.disableInteractiveSerialConsole(request: r, options: o)
        })
    }

    public func detachLun(
      request: DetachLunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "detachLun",
        action: {
          (r: DetachLunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.detachLun(request: r, options: o)
        })
    }

    public func listSshkeys(
      request: ListSSHKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListSSHKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSshkeys",
        action: {
          (r: ListSSHKeysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListSSHKeysResponse
          in
          return try await self.inner.listSshkeys(request: r, options: o)
        })
    }

    public func createSshkey(
      request: CreateSSHKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.SSHKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSshkey",
        action: {
          (r: CreateSSHKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.SSHKey
          in
          return try await self.inner.createSshkey(request: r, options: o)
        })
    }

    public func deleteSshkey(
      request: DeleteSSHKeyRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSshkey",
        action: { (r: DeleteSSHKeyRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSshkey(request: r, options: o)
        })
    }

    public func listVolumes(
      request: ListVolumesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListVolumesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVolumes",
        action: {
          (r: ListVolumesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListVolumesResponse
          in
          return try await self.inner.listVolumes(request: r, options: o)
        })
    }

    public func getVolume(
      request: GetVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Volume {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVolume",
        action: {
          (r: GetVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Volume
          in
          return try await self.inner.getVolume(request: r, options: o)
        })
    }

    public func updateVolume(
      request: UpdateVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateVolume",
        action: {
          (r: UpdateVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateVolume(request: r, options: o)
        })
    }

    public func renameVolume(
      request: RenameVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Volume {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameVolume",
        action: {
          (r: RenameVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Volume
          in
          return try await self.inner.renameVolume(request: r, options: o)
        })
    }

    public func evictVolume(
      request: EvictVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "evictVolume",
        action: {
          (r: EvictVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.evictVolume(request: r, options: o)
        })
    }

    public func resizeVolume(
      request: ResizeVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resizeVolume",
        action: {
          (r: ResizeVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resizeVolume(request: r, options: o)
        })
    }

    public func listNetworks(
      request: ListNetworksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListNetworksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNetworks",
        action: {
          (r: ListNetworksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListNetworksResponse
          in
          return try await self.inner.listNetworks(request: r, options: o)
        })
    }

    public func listNetworkUsage(
      request: ListNetworkUsageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListNetworkUsageResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNetworkUsage",
        action: {
          (r: ListNetworkUsageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListNetworkUsageResponse
          in
          return try await self.inner.listNetworkUsage(request: r, options: o)
        })
    }

    public func getNetwork(
      request: GetNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Network {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNetwork",
        action: {
          (r: GetNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Network
          in
          return try await self.inner.getNetwork(request: r, options: o)
        })
    }

    public func updateNetwork(
      request: UpdateNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNetwork",
        action: {
          (r: UpdateNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateNetwork(request: r, options: o)
        })
    }

    public func createVolumeSnapshot(
      request: CreateVolumeSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.VolumeSnapshot {
      try await self._intercept(
        request: request,
        options: options,
        name: "createVolumeSnapshot",
        action: {
          (r: CreateVolumeSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.VolumeSnapshot
          in
          return try await self.inner.createVolumeSnapshot(request: r, options: o)
        })
    }

    public func restoreVolumeSnapshot(
      request: RestoreVolumeSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "restoreVolumeSnapshot",
        action: {
          (r: RestoreVolumeSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreVolumeSnapshot(request: r, options: o)
        })
    }

    public func deleteVolumeSnapshot(
      request: DeleteVolumeSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteVolumeSnapshot",
        action: {
          (r: DeleteVolumeSnapshotRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteVolumeSnapshot(request: r, options: o)
        })
    }

    public func getVolumeSnapshot(
      request: GetVolumeSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.VolumeSnapshot {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVolumeSnapshot",
        action: {
          (r: GetVolumeSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.VolumeSnapshot
          in
          return try await self.inner.getVolumeSnapshot(request: r, options: o)
        })
    }

    public func listVolumeSnapshots(
      request: ListVolumeSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListVolumeSnapshotsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVolumeSnapshots",
        action: {
          (r: ListVolumeSnapshotsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListVolumeSnapshotsResponse
          in
          return try await self.inner.listVolumeSnapshots(request: r, options: o)
        })
    }

    public func getLun(
      request: GetLunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Lun {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLun",
        action: {
          (r: GetLunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Lun
          in
          return try await self.inner.getLun(request: r, options: o)
        })
    }

    public func listLuns(
      request: ListLunsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListLunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLuns",
        action: {
          (r: ListLunsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListLunsResponse
          in
          return try await self.inner.listLuns(request: r, options: o)
        })
    }

    public func evictLun(
      request: EvictLunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "evictLun",
        action: {
          (r: EvictLunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.evictLun(request: r, options: o)
        })
    }

    public func getNfsShare(
      request: GetNfsShareRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.NfsShare {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNfsShare",
        action: {
          (r: GetNfsShareRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.NfsShare
          in
          return try await self.inner.getNfsShare(request: r, options: o)
        })
    }

    public func listNfsShares(
      request: ListNfsSharesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListNfsSharesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNfsShares",
        action: {
          (r: ListNfsSharesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListNfsSharesResponse
          in
          return try await self.inner.listNfsShares(request: r, options: o)
        })
    }

    public func updateNfsShare(
      request: UpdateNfsShareRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNfsShare",
        action: {
          (r: UpdateNfsShareRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateNfsShare(request: r, options: o)
        })
    }

    public func createNfsShare(
      request: CreateNfsShareRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNfsShare",
        action: {
          (r: CreateNfsShareRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createNfsShare(request: r, options: o)
        })
    }

    public func renameNfsShare(
      request: RenameNfsShareRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.NfsShare {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameNfsShare",
        action: {
          (r: RenameNfsShareRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.NfsShare
          in
          return try await self.inner.renameNfsShare(request: r, options: o)
        })
    }

    public func deleteNfsShare(
      request: DeleteNfsShareRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNfsShare",
        action: {
          (r: DeleteNfsShareRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteNfsShare(request: r, options: o)
        })
    }

    public func listProvisioningQuotas(
      request: ListProvisioningQuotasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListProvisioningQuotasResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProvisioningQuotas",
        action: {
          (r: ListProvisioningQuotasRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListProvisioningQuotasResponse
          in
          return try await self.inner.listProvisioningQuotas(request: r, options: o)
        })
    }

    public func submitProvisioningConfig(
      request: SubmitProvisioningConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.SubmitProvisioningConfigResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "submitProvisioningConfig",
        action: {
          (r: SubmitProvisioningConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.SubmitProvisioningConfigResponse
          in
          return try await self.inner.submitProvisioningConfig(request: r, options: o)
        })
    }

    public func getProvisioningConfig(
      request: GetProvisioningConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProvisioningConfig",
        action: {
          (r: GetProvisioningConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig
          in
          return try await self.inner.getProvisioningConfig(request: r, options: o)
        })
    }

    public func createProvisioningConfig(
      request: CreateProvisioningConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createProvisioningConfig",
        action: {
          (r: CreateProvisioningConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig
          in
          return try await self.inner.createProvisioningConfig(request: r, options: o)
        })
    }

    public func updateProvisioningConfig(
      request: UpdateProvisioningConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateProvisioningConfig",
        action: {
          (r: UpdateProvisioningConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ProvisioningConfig
          in
          return try await self.inner.updateProvisioningConfig(request: r, options: o)
        })
    }

    public func renameNetwork(
      request: RenameNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.Network {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameNetwork",
        action: {
          (r: RenameNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.Network
          in
          return try await self.inner.renameNetwork(request: r, options: o)
        })
    }

    public func listOsimages(
      request: ListOSImagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBareMetalSolutionV2.ListOSImagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOsimages",
        action: {
          (r: ListOSImagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBareMetalSolutionV2.ListOSImagesResponse
          in
          return try await self.inner.listOsimages(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
