// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration parameters for a new instance.
public struct InstanceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the instance config.
  public var name: Swift.String = Swift.String()

  /// A transient unique identifier to idenfity an instance within an
  /// ProvisioningConfig request.
  public var id: Swift.String = Swift.String()

  /// Instance type.
  /// [Available
  /// types](https://cloud.google.com/bare-metal/docs/bms-planning#server_configurations)
  public var instanceType: Swift.String = Swift.String()

  /// Whether the instance should be provisioned with Hyperthreading enabled.
  public var hyperthreading: Swift.Bool = Swift.Bool()

  /// OS image to initialize the instance.
  /// [Available
  /// images](https://cloud.google.com/bare-metal/docs/bms-planning#server_configurations)
  public var osImage: Swift.String = Swift.String()

  /// Client network address. Filled if InstanceConfig.multivlan_config is false.
  @available(*, deprecated)
  public var clientNetwork: InstanceConfig.NetworkAddress? = nil

  /// Private network address, if any. Filled if InstanceConfig.multivlan_config
  /// is false.
  @available(*, deprecated)
  public var privateNetwork: InstanceConfig.NetworkAddress? = nil

  /// User note field, it can be used by customers to add additional information
  /// for the BMS Ops team .
  public var userNote: Swift.String = Swift.String()

  /// If true networks can be from different projects of the same vendor account.
  public var accountNetworksEnabled: Swift.Bool = Swift.Bool()

  /// The type of network configuration on the instance.
  public var networkConfig: InstanceConfig.NetworkConfig = InstanceConfig.NetworkConfig()

  /// Server network template name. Filled if InstanceConfig.multivlan_config is
  /// true.
  public var networkTemplate: Swift.String = Swift.String()

  /// List of logical interfaces for the instance. The number of logical
  /// interfaces will be the same as number of hardware bond/nic on the chosen
  /// network template. Filled if InstanceConfig.multivlan_config is true.
  public var logicalInterfaces: [LogicalInterface] = []

  /// List of names of ssh keys used to provision the instance.
  public var sshKeyNames: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `InstanceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InstanceConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let id = CodingKeys(stringValue: "id")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let hyperthreading = CodingKeys(stringValue: "hyperthreading")
    static let osImage = CodingKeys(stringValue: "osImage")
    static let clientNetwork = CodingKeys(stringValue: "clientNetwork")
    static let privateNetwork = CodingKeys(stringValue: "privateNetwork")
    static let userNote = CodingKeys(stringValue: "userNote")
    static let accountNetworksEnabled = CodingKeys(stringValue: "accountNetworksEnabled")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")
    static let networkTemplate = CodingKeys(stringValue: "networkTemplate")
    static let logicalInterfaces = CodingKeys(stringValue: "logicalInterfaces")
    static let sshKeyNames = CodingKeys(stringValue: "sshKeyNames")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "id",
      "instanceType",
      "hyperthreading",
      "osImage",
      "clientNetwork",
      "privateNetwork",
      "userNote",
      "accountNetworksEnabled",
      "networkConfig",
      "networkTemplate",
      "logicalInterfaces",
      "sshKeyNames",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceType) {
      self.instanceType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hyperthreading) {
      self.hyperthreading = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osImage) {
      self.osImage = value
    }
    self.clientNetwork = try container.decodeIfPresent(
      InstanceConfig.NetworkAddress.self, forKey: .clientNetwork)
    self.privateNetwork = try container.decodeIfPresent(
      InstanceConfig.NetworkAddress.self, forKey: .privateNetwork)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userNote) {
      self.userNote = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .accountNetworksEnabled) {
      self.accountNetworksEnabled = value
    }
    if let value = try container.decodeIfPresent(
      InstanceConfig.NetworkConfig.self, forKey: .networkConfig)
    {
      self.networkConfig = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkTemplate) {
      self.networkTemplate = value
    }
    if let value = try container.decodeIfPresent(
      [LogicalInterface].self, forKey: .logicalInterfaces)
    {
      self.logicalInterfaces = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sshKeyNames) {
      self.sshKeyNames = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encode(self.hyperthreading, forKey: .hyperthreading)
    try container.encode(self.osImage, forKey: .osImage)
    try container.encodeIfPresent(self.clientNetwork, forKey: .clientNetwork)
    try container.encodeIfPresent(self.privateNetwork, forKey: .privateNetwork)
    try container.encode(self.userNote, forKey: .userNote)
    try container.encode(self.accountNetworksEnabled, forKey: .accountNetworksEnabled)
    try container.encode(self.networkConfig, forKey: .networkConfig)
    try container.encode(self.networkTemplate, forKey: .networkTemplate)
    try container.encode(self.logicalInterfaces, forKey: .logicalInterfaces)
    try container.encode(self.sshKeyNames, forKey: .sshKeyNames)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A network.
  public struct NetworkAddress: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Id of the network to use, within the same ProvisioningConfig request.
    public var networkId: Swift.String = Swift.String()

    /// IPv4 address to be assigned to the server.
    public var address: Swift.String = Swift.String()

    /// Name of the existing network to use.
    public var existingNetworkId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `NetworkAddress`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NetworkAddress().with { $0.networkId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let networkId = CodingKeys(stringValue: "networkId")
      static let address = CodingKeys(stringValue: "address")
      static let existingNetworkId = CodingKeys(stringValue: "existingNetworkId")

      static let _knownKeys: Set<Swift.String> = [
        "networkId",
        "address",
        "existingNetworkId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkId) {
        self.networkId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .address) {
        self.address = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .existingNetworkId) {
        self.existingNetworkId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.networkId, forKey: .networkId)
      try container.encode(self.address, forKey: .address)
      try container.encode(self.existingNetworkId, forKey: .existingNetworkId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.InstanceConfig.NetworkAddress"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The network configuration of the instance.
  public enum NetworkConfig: Codable, Equatable, Sendable {
    /// The unspecified network configuration.
    case networkconfigUnspecified
    /// Instance part of single client network and single private network.
    case singleVlan
    /// Instance part of multiple (or single) client networks and private
    /// networks.
    case multiVlan
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .networkconfigUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .networkconfigUnspecified: return 0
      case .singleVlan: return 1
      case .multiVlan: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .networkconfigUnspecified: return "NETWORKCONFIG_UNSPECIFIED"
      case .singleVlan: return "SINGLE_VLAN"
      case .multiVlan: return "MULTI_VLAN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NetworkConfig/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NETWORKCONFIG_UNSPECIFIED": self = .networkconfigUnspecified
      case "SINGLE_VLAN": self = .singleVlan
      case "MULTI_VLAN": self = .multiVlan
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NetworkConfig/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .networkconfigUnspecified
      case 1: self = .singleVlan
      case 2: self = .multiVlan
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .networkconfigUnspecified: return try container.encode("NETWORKCONFIG_UNSPECIFIED")
      case .singleVlan: return try container.encode("SINGLE_VLAN")
      case .multiVlan: return try container.encode("MULTI_VLAN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.InstanceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
