// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A server.
public struct Instance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of this `Instance`.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// Format:
  /// `projects/{project}/locations/{location}/instances/{instance}`
  public var name: Swift.String = Swift.String()

  /// Output only. An identifier for the `Instance`, generated by the backend.
  public var id: Swift.String = Swift.String()

  /// Output only. Create a time stamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update a time stamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Immutable. The server type.
  /// [Available server
  /// types](https://cloud.google.com/bare-metal/docs/bms-planning#server_configurations)
  public var machineType: Swift.String = Swift.String()

  /// Output only. The state of the server.
  public var state: Instance.State = Instance.State()

  /// True if you enable hyperthreading for the server, otherwise false.
  /// The default value is false.
  public var hyperthreadingEnabled: Swift.Bool = Swift.Bool()

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Immutable. List of LUNs associated with this server.
  public var luns: [Lun] = []

  /// Input only. List of Volumes to attach to this Instance on creation.
  /// This field won't be populated in Get/List responses.
  public var volumes: [Volume] = []

  /// Output only. List of networks associated with this server.
  public var networks: [Network] = []

  /// Output only. True if the interactive serial console feature is enabled for
  /// the instance, false otherwise. The default value is false.
  public var interactiveSerialConsoleEnabled: Swift.Bool = Swift.Bool()

  /// The OS image currently installed on the server.
  public var osImage: Swift.String = Swift.String()

  /// Immutable. Pod name.
  /// Pod is an independent part of infrastructure.
  /// Instance can be connected to the assets (networks, volumes) allocated
  /// in the same pod only.
  public var pod: Swift.String = Swift.String()

  /// Instance network template name. For eg, bondaa-bondaa, bondab-nic, etc.
  /// Generally, the template name follows the syntax of
  /// "bond<bond_mode>" or "nic".
  public var networkTemplate: Swift.String = Swift.String()

  /// List of logical interfaces for the instance. The number of logical
  /// interfaces will be the same as number of hardware bond/nic on the chosen
  /// network template. For the non-multivlan configurations (for eg, existing
  /// servers) that use existing default network template (bondaa-bondaa), both
  /// the Instance.networks field and the Instance.logical_interfaces fields will
  /// be filled to ensure backward compatibility. For the others, only
  /// Instance.logical_interfaces will be filled.
  public var logicalInterfaces: [LogicalInterface] = []

  /// Output only. Text field about info for logging in.
  public var loginInfo: Swift.String = Swift.String()

  /// The workload profile for the instance.
  public var workloadProfile: WorkloadProfile = WorkloadProfile()

  /// Output only. The firmware version for the instance.
  public var firmwareVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible states for this server.
  public enum State: Codable, Equatable, Sendable {
    /// The server is in an unknown state.
    case unspecified
    /// The server is being provisioned.
    case provisioning
    /// The server is running.
    case running
    /// The server has been deleted.
    case deleted
    /// The server is being updated.
    case updating
    /// The server is starting.
    case starting
    /// The server is stopping.
    case stopping
    /// The server is shutdown.
    case shutdown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .running: return 2
      case .deleted: return 3
      case .updating: return 4
      case .starting: return 5
      case .stopping: return 6
      case .shutdown: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .running: return "RUNNING"
      case .deleted: return "DELETED"
      case .updating: return "UPDATING"
      case .starting: return "STARTING"
      case .stopping: return "STOPPING"
      case .shutdown: return "SHUTDOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "RUNNING": self = .running
      case "DELETED": self = .deleted
      case "UPDATING": self = .updating
      case "STARTING": self = .starting
      case "STOPPING": self = .stopping
      case "SHUTDOWN": self = .shutdown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .running
      case 3: self = .deleted
      case 4: self = .updating
      case 5: self = .starting
      case 6: self = .stopping
      case 7: self = .shutdown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .running: return try container.encode(2)
      case .deleted: return try container.encode(3)
      case .updating: return try container.encode(4)
      case .starting: return try container.encode(5)
      case .stopping: return try container.encode(6)
      case .shutdown: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.Instance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
