// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource budget.
public struct InstanceQuota: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the instance quota.
  public var name: Swift.String = Swift.String()

  /// Instance type.
  /// Deprecated: use gcp_service.
  @available(*, deprecated)
  public var instanceType: Swift.String = Swift.String()

  /// The gcp service of the provisioning quota.
  public var gcpService: Swift.String = Swift.String()

  /// Location where the quota applies.
  public var location: Swift.String = Swift.String()

  /// Number of machines than can be created for the given location and
  /// instance_type.
  public var availableMachineCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `InstanceQuota`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InstanceQuota().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let gcpService = CodingKeys(stringValue: "gcpService")
    static let location = CodingKeys(stringValue: "location")
    static let availableMachineCount = CodingKeys(stringValue: "availableMachineCount")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "instanceType",
      "gcpService",
      "location",
      "availableMachineCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceType) {
      self.instanceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpService) {
      self.gcpService = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .availableMachineCount) {
      self.availableMachineCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encode(self.gcpService, forKey: .gcpService)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.availableMachineCount, forKey: .availableMachineCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.InstanceQuota"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
