// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Each logical interface represents a logical abstraction of the underlying
/// physical interface (for eg. bond, nic) of the instance. Each logical
/// interface can effectively map to multiple network-IP pairs and still be
/// mapped to one underlying physical interface.
public struct LogicalInterface: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// List of logical network interfaces within a logical interface.
  public var logicalNetworkInterfaces: [LogicalInterface.LogicalNetworkInterface] = []

  /// Interface name. This is of syntax <bond><bond_mode> or <nic> and
  /// forms part of the network template name.
  public var name: Swift.String = Swift.String()

  /// The index of the logical interface mapping to the index of the hardware
  /// bond or nic on the chosen network template. This field is deprecated.
  @available(*, deprecated)
  public var interfaceIndex: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LogicalInterface`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogicalInterface().with { $0.logicalNetworkInterfaces = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let logicalNetworkInterfaces = CodingKeys(stringValue: "logicalNetworkInterfaces")
    static let name = CodingKeys(stringValue: "name")
    static let interfaceIndex = CodingKeys(stringValue: "interfaceIndex")

    static let _knownKeys: Set<Swift.String> = [
      "logicalNetworkInterfaces",
      "name",
      "interfaceIndex",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [LogicalInterface.LogicalNetworkInterface].self, forKey: .logicalNetworkInterfaces)
    {
      self.logicalNetworkInterfaces = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .interfaceIndex) {
      self.interfaceIndex = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.logicalNetworkInterfaces, forKey: .logicalNetworkInterfaces)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.interfaceIndex, forKey: .interfaceIndex)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Each logical network interface is effectively a network and IP pair.
  public struct LogicalNetworkInterface: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of the network
    public var network: Swift.String = Swift.String()

    /// IP address in the network
    public var ipAddress: Swift.String = Swift.String()

    /// Whether this interface is the default gateway for the instance. Only
    /// one interface can be the default gateway for the instance.
    public var defaultGateway: Swift.Bool = Swift.Bool()

    /// Type of network.
    public var networkType: Network.Type_ = Network.Type_()

    /// An identifier for the `Network`, generated by the backend.
    public var id: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LogicalNetworkInterface`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LogicalNetworkInterface().with { $0.network = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let network = CodingKeys(stringValue: "network")
      static let ipAddress = CodingKeys(stringValue: "ipAddress")
      static let defaultGateway = CodingKeys(stringValue: "defaultGateway")
      static let networkType = CodingKeys(stringValue: "networkType")
      static let id = CodingKeys(stringValue: "id")

      static let _knownKeys: Set<Swift.String> = [
        "network",
        "ipAddress",
        "defaultGateway",
        "networkType",
        "id",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
        self.ipAddress = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .defaultGateway) {
        self.defaultGateway = value
      }
      if let value = try container.decodeIfPresent(Network.Type_.self, forKey: .networkType) {
        self.networkType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.ipAddress, forKey: .ipAddress)
      try container.encode(self.defaultGateway, forKey: .defaultGateway)
      try container.encode(self.networkType, forKey: .networkType)
      try container.encode(self.id, forKey: .id)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.baremetalsolution.v2.LogicalInterface.LogicalNetworkInterface"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.LogicalInterface"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
