// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Network.
public struct Network: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this `Network`.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// Format:
  /// `projects/{project}/locations/{location}/networks/{network}`
  public var name: Swift.String = Swift.String()

  /// An identifier for the `Network`, generated by the backend.
  public var id: Swift.String = Swift.String()

  /// The type of this network.
  public var type: Network.Type_ = Network.Type_()

  /// IP address configured.
  public var ipAddress: Swift.String = Swift.String()

  /// List of physical interfaces.
  public var macAddress: [Swift.String] = []

  /// The Network state.
  public var state: Network.State = Network.State()

  /// The vlan id of the Network.
  public var vlanId: Swift.String = Swift.String()

  /// The cidr of the Network.
  public var cidr: Swift.String = Swift.String()

  /// The vrf for the Network.
  public var vrf: VRF? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// IP range for reserved for services (e.g. NFS).
  public var servicesCidr: Swift.String = Swift.String()

  /// List of IP address reservations in this network.
  /// When updating this field, an error will be generated if a reservation
  /// conflicts with an IP address already allocated to a physical server.
  public var reservations: [NetworkAddressReservation] = []

  /// Output only. Pod name.
  public var pod: Swift.String = Swift.String()

  /// Input only. List of mount points to attach the network to.
  public var mountPoints: [NetworkMountPoint] = []

  /// Whether network uses standard frames or jumbo ones.
  public var jumboFramesEnabled: Swift.Bool = Swift.Bool()

  /// Output only. Gateway ip address.
  public var gatewayIp: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Network`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Network().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let id = CodingKeys(stringValue: "id")
    static let type = CodingKeys(stringValue: "type")
    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let macAddress = CodingKeys(stringValue: "macAddress")
    static let state = CodingKeys(stringValue: "state")
    static let vlanId = CodingKeys(stringValue: "vlanId")
    static let cidr = CodingKeys(stringValue: "cidr")
    static let vrf = CodingKeys(stringValue: "vrf")
    static let labels = CodingKeys(stringValue: "labels")
    static let servicesCidr = CodingKeys(stringValue: "servicesCidr")
    static let reservations = CodingKeys(stringValue: "reservations")
    static let pod = CodingKeys(stringValue: "pod")
    static let mountPoints = CodingKeys(stringValue: "mountPoints")
    static let jumboFramesEnabled = CodingKeys(stringValue: "jumboFramesEnabled")
    static let gatewayIp = CodingKeys(stringValue: "gatewayIp")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "id",
      "type",
      "ipAddress",
      "macAddress",
      "state",
      "vlanId",
      "cidr",
      "vrf",
      "labels",
      "servicesCidr",
      "reservations",
      "pod",
      "mountPoints",
      "jumboFramesEnabled",
      "gatewayIp",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Network.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .macAddress) {
      self.macAddress = value
    }
    if let value = try container.decodeIfPresent(Network.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vlanId) {
      self.vlanId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cidr) {
      self.cidr = value
    }
    self.vrf = try container.decodeIfPresent(VRF.self, forKey: .vrf)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .servicesCidr) {
      self.servicesCidr = value
    }
    if let value = try container.decodeIfPresent(
      [NetworkAddressReservation].self, forKey: .reservations)
    {
      self.reservations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pod) {
      self.pod = value
    }
    if let value = try container.decodeIfPresent([NetworkMountPoint].self, forKey: .mountPoints) {
      self.mountPoints = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .jumboFramesEnabled) {
      self.jumboFramesEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gatewayIp) {
      self.gatewayIp = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.macAddress, forKey: .macAddress)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.vlanId, forKey: .vlanId)
    try container.encode(self.cidr, forKey: .cidr)
    try container.encodeIfPresent(self.vrf, forKey: .vrf)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.servicesCidr, forKey: .servicesCidr)
    try container.encode(self.reservations, forKey: .reservations)
    try container.encode(self.pod, forKey: .pod)
    try container.encode(self.mountPoints, forKey: .mountPoints)
    try container.encode(self.jumboFramesEnabled, forKey: .jumboFramesEnabled)
    try container.encode(self.gatewayIp, forKey: .gatewayIp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Network type.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unspecified value.
    case unspecified
    /// Client network, a network peered to a Google Cloud VPC.
    case client
    /// Private network, a network local to the Bare Metal Solution environment.
    case `private`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .client: return 1
      case .`private`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .client: return "CLIENT"
      case .`private`: return "PRIVATE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "CLIENT": self = .client
      case "PRIVATE": self = .`private`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .client
      case 2: self = .`private`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .client: return try container.encode("CLIENT")
      case .`private`: return try container.encode("PRIVATE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible states for this Network.
  public enum State: Codable, Equatable, Sendable {
    /// The Network is in an unknown state.
    case unspecified
    /// The Network is provisioning.
    case provisioning
    /// The Network has been provisioned.
    case provisioned
    /// The Network is being deprovisioned.
    case deprovisioning
    /// The Network is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .provisioned: return 2
      case .deprovisioning: return 3
      case .updating: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .provisioned: return "PROVISIONED"
      case .deprovisioning: return "DEPROVISIONING"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "PROVISIONED": self = .provisioned
      case "DEPROVISIONING": self = .deprovisioning
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .provisioned
      case 3: self = .deprovisioning
      case 4: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .provisioned: return try container.encode("PROVISIONED")
      case .deprovisioning: return try container.encode("DEPROVISIONING")
      case .updating: return try container.encode("UPDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.Network"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
