// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A reservation of one or more addresses in a network.
public struct NetworkAddressReservation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The first address of this reservation block.
  /// Must be specified as a single IPv4 address, e.g. 10.1.2.2.
  public var startAddress: Swift.String = Swift.String()

  /// The last address of this reservation block, inclusive. I.e., for cases when
  /// reservations are only single addresses, end_address and start_address will
  /// be the same.
  /// Must be specified as a single IPv4 address, e.g. 10.1.2.2.
  public var endAddress: Swift.String = Swift.String()

  /// A note about this reservation, intended for human consumption.
  public var note: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkAddressReservation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkAddressReservation().with { $0.startAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startAddress = CodingKeys(stringValue: "startAddress")
    static let endAddress = CodingKeys(stringValue: "endAddress")
    static let note = CodingKeys(stringValue: "note")

    static let _knownKeys: Set<Swift.String> = [
      "startAddress",
      "endAddress",
      "note",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .startAddress) {
      self.startAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .endAddress) {
      self.endAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .note) {
      self.note = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.startAddress, forKey: .startAddress)
    try container.encode(self.endAddress, forKey: .endAddress)
    try container.encode(self.note, forKey: .note)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.NetworkAddressReservation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
