// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Mount point for a network.
public struct NetworkMountPoint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Instance to attach network to.
  public var instance: Swift.String = Swift.String()

  /// Logical interface to detach from.
  public var logicalInterface: Swift.String = Swift.String()

  /// Network should be a default gateway.
  public var defaultGateway: Swift.Bool = Swift.Bool()

  /// Ip address of the server.
  public var ipAddress: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkMountPoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkMountPoint().with { $0.instance = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let instance = CodingKeys(stringValue: "instance")
    static let logicalInterface = CodingKeys(stringValue: "logicalInterface")
    static let defaultGateway = CodingKeys(stringValue: "defaultGateway")
    static let ipAddress = CodingKeys(stringValue: "ipAddress")

    static let _knownKeys: Set<Swift.String> = [
      "instance",
      "logicalInterface",
      "defaultGateway",
      "ipAddress",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
      self.instance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logicalInterface) {
      self.logicalInterface = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .defaultGateway) {
      self.defaultGateway = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instance, forKey: .instance)
    try container.encode(self.logicalInterface, forKey: .logicalInterface)
    try container.encode(self.defaultGateway, forKey: .defaultGateway)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.NetworkMountPoint"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
