// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An NFS share.
public struct NfsShare: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of the NFS share.
  public var name: Swift.String = Swift.String()

  /// Output only. An identifier for the NFS share, generated by the backend.
  /// This field will be deprecated in the future, use `id` instead.
  public var nfsShareId: Swift.String = Swift.String()

  /// Output only. An identifier for the NFS share, generated by the backend.
  /// This is the same value as nfs_share_id and will replace it in the future.
  public var id: Swift.String = Swift.String()

  /// Output only. The state of the NFS share.
  public var state: NfsShare.State = NfsShare.State()

  /// Output only. The underlying volume of the share. Created automatically
  /// during provisioning.
  public var volume: Swift.String = Swift.String()

  /// List of allowed access points.
  public var allowedClients: [NfsShare.AllowedClient] = []

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The requested size, in GiB.
  public var requestedSizeGib: Swift.Int64 = Swift.Int64()

  /// Immutable. The storage type of the underlying volume.
  public var storageType: NfsShare.StorageType = NfsShare.StorageType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NfsShare`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NfsShare().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let nfsShareId = CodingKeys(stringValue: "nfsShareId")
    static let id = CodingKeys(stringValue: "id")
    static let state = CodingKeys(stringValue: "state")
    static let volume = CodingKeys(stringValue: "volume")
    static let allowedClients = CodingKeys(stringValue: "allowedClients")
    static let labels = CodingKeys(stringValue: "labels")
    static let requestedSizeGib = CodingKeys(stringValue: "requestedSizeGib")
    static let storageType = CodingKeys(stringValue: "storageType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "nfsShareId",
      "id",
      "state",
      "volume",
      "allowedClients",
      "labels",
      "requestedSizeGib",
      "storageType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nfsShareId) {
      self.nfsShareId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(NfsShare.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .volume) {
      self.volume = value
    }
    if let value = try container.decodeIfPresent(
      [NfsShare.AllowedClient].self, forKey: .allowedClients)
    {
      self.allowedClients = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .requestedSizeGib) {
      self.requestedSizeGib = value
    }
    if let value = try container.decodeIfPresent(NfsShare.StorageType.self, forKey: .storageType) {
      self.storageType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.nfsShareId, forKey: .nfsShareId)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.volume, forKey: .volume)
    try container.encode(self.allowedClients, forKey: .allowedClients)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.requestedSizeGib, forKey: .requestedSizeGib)
    try container.encode(self.storageType, forKey: .storageType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents an 'access point' for the share.
  public struct AllowedClient: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The network the access point sits on.
    public var network: Swift.String = Swift.String()

    /// Output only. The IP address of the share on this network. Assigned
    /// automatically during provisioning based on the network's services_cidr.
    public var shareIp: Swift.String = Swift.String()

    /// The subnet of IP addresses permitted to access the share.
    public var allowedClientsCidr: Swift.String = Swift.String()

    /// Mount permissions.
    public var mountPermissions: NfsShare.MountPermissions = NfsShare.MountPermissions()

    /// Allow dev flag.  Which controls whether to allow creation of devices.
    public var allowDev: Swift.Bool = Swift.Bool()

    /// Allow the setuid flag.
    public var allowSuid: Swift.Bool = Swift.Bool()

    /// Disable root squashing, which is a feature of NFS.
    /// Root squash is a special mapping of the remote superuser (root) identity
    /// when using identity authentication.
    public var noRootSquash: Swift.Bool = Swift.Bool()

    /// Output only. The path to access NFS, in format shareIP:/InstanceID
    /// InstanceID is the generated ID instead of customer provided name.
    /// example like "10.0.0.0:/g123456789-nfs001"
    public var nfsPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AllowedClient`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllowedClient().with { $0.network = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let network = CodingKeys(stringValue: "network")
      static let shareIp = CodingKeys(stringValue: "shareIp")
      static let allowedClientsCidr = CodingKeys(stringValue: "allowedClientsCidr")
      static let mountPermissions = CodingKeys(stringValue: "mountPermissions")
      static let allowDev = CodingKeys(stringValue: "allowDev")
      static let allowSuid = CodingKeys(stringValue: "allowSuid")
      static let noRootSquash = CodingKeys(stringValue: "noRootSquash")
      static let nfsPath = CodingKeys(stringValue: "nfsPath")

      static let _knownKeys: Set<Swift.String> = [
        "network",
        "shareIp",
        "allowedClientsCidr",
        "mountPermissions",
        "allowDev",
        "allowSuid",
        "noRootSquash",
        "nfsPath",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shareIp) {
        self.shareIp = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .allowedClientsCidr) {
        self.allowedClientsCidr = value
      }
      if let value = try container.decodeIfPresent(
        NfsShare.MountPermissions.self, forKey: .mountPermissions)
      {
        self.mountPermissions = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowDev) {
        self.allowDev = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowSuid) {
        self.allowSuid = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .noRootSquash) {
        self.noRootSquash = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nfsPath) {
        self.nfsPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.shareIp, forKey: .shareIp)
      try container.encode(self.allowedClientsCidr, forKey: .allowedClientsCidr)
      try container.encode(self.mountPermissions, forKey: .mountPermissions)
      try container.encode(self.allowDev, forKey: .allowDev)
      try container.encode(self.allowSuid, forKey: .allowSuid)
      try container.encode(self.noRootSquash, forKey: .noRootSquash)
      try container.encode(self.nfsPath, forKey: .nfsPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.NfsShare.AllowedClient"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible states for this NFS share.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The share is in an unknown state.
    case unspecified
    /// The share has been provisioned.
    case provisioned
    /// The NFS Share is being created.
    case creating
    /// The NFS Share is being updated.
    case updating
    /// The NFS Share has been requested to be deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioned: return 1
      case .creating: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioned: return "PROVISIONED"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONED": self = .provisioned
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioned
      case 2: self = .creating
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .provisioned: return try container.encode("PROVISIONED")
      case .creating: return try container.encode("CREATING")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible mount permissions.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum MountPermissions: Codable, Equatable, Sendable {
    /// Permissions were not specified.
    case unspecified
    /// NFS share can be mount with read-only permissions.
    case read
    /// NFS share can be mount with read-write permissions.
    case readWrite
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .read: return 1
      case .readWrite: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MOUNT_PERMISSIONS_UNSPECIFIED"
      case .read: return "READ"
      case .readWrite: return "READ_WRITE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MountPermissions/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MOUNT_PERMISSIONS_UNSPECIFIED": self = .unspecified
      case "READ": self = .read
      case "READ_WRITE": self = .readWrite
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MountPermissions/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .read
      case 2: self = .readWrite
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("MOUNT_PERMISSIONS_UNSPECIFIED")
      case .read: return try container.encode("READ")
      case .readWrite: return try container.encode("READ_WRITE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The storage type for a volume.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum StorageType: Codable, Equatable, Sendable {
    /// The storage type for this volume is unknown.
    case unspecified
    /// The storage type for this volume is SSD.
    case ssd
    /// This storage type for this volume is HDD.
    case hdd
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ssd: return 1
      case .hdd: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STORAGE_TYPE_UNSPECIFIED"
      case .ssd: return "SSD"
      case .hdd: return "HDD"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StorageType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STORAGE_TYPE_UNSPECIFIED": self = .unspecified
      case "SSD": self = .ssd
      case "HDD": self = .hdd
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StorageType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ssd
      case 2: self = .hdd
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STORAGE_TYPE_UNSPECIFIED")
      case .ssd: return try container.encode("SSD")
      case .hdd: return try container.encode("HDD")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.NfsShare"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
