// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A provisioning configuration.
public struct ProvisioningConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The system-generated name of the provisioning config. This
  /// follows the UUID format.
  public var name: Swift.String = Swift.String()

  /// Instances to be created.
  public var instances: [InstanceConfig] = []

  /// Networks to be created.
  public var networks: [NetworkConfig] = []

  /// Volumes to be created.
  public var volumes: [VolumeConfig] = []

  /// A generated ticket id to track provisioning request.
  public var ticketId: Swift.String = Swift.String()

  /// A service account to enable customers to access instance credentials upon
  /// handover.
  public var handoverServiceAccount: Swift.String = Swift.String()

  /// Email provided to send a confirmation with provisioning config to.
  /// Deprecated in favour of email field in request messages.
  @available(*, deprecated)
  public var email: Swift.String = Swift.String()

  /// Output only. State of ProvisioningConfig.
  public var state: ProvisioningConfig.State = ProvisioningConfig.State()

  /// Optional. Location name of this ProvisioningConfig.
  /// It is optional only for Intake UI transition period.
  public var location: Swift.String = Swift.String()

  /// Output only. Last update timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. URI to Cloud Console UI view of this provisioning config.
  public var cloudConsoleUri: Swift.String = Swift.String()

  /// If true, VPC SC is enabled for the cluster.
  public var vpcScEnabled: Swift.Bool = Swift.Bool()

  /// Optional status messages associated with the FAILED state.
  public var statusMessage: Swift.String = Swift.String()

  /// Optional. The user-defined identifier of the provisioning config.
  public var customId: Swift.String = Swift.String()

  /// Initialize a new instance of `ProvisioningConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProvisioningConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible states for this ProvisioningConfig.
  public enum State: Codable, Equatable, Sendable {
    /// State wasn't specified.
    case unspecified
    /// ProvisioningConfig is a draft and can be freely modified.
    case draft
    /// ProvisioningConfig was already submitted and cannot be modified.
    case submitted
    /// ProvisioningConfig was in the provisioning state.  Initially this state
    /// comes from the work order table in big query when SNOW is used.  Later
    /// this field can be set by the work order API.
    case provisioning
    /// ProvisioningConfig was provisioned, meaning the resources exist.
    case provisioned
    /// ProvisioningConfig was validated.  A validation tool will be run to
    /// set this state.
    case validated
    /// ProvisioningConfig was canceled.
    case cancelled
    /// The request is submitted for provisioning, with error return.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .draft: return 1
      case .submitted: return 2
      case .provisioning: return 3
      case .provisioned: return 4
      case .validated: return 5
      case .cancelled: return 6
      case .failed: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .draft: return "DRAFT"
      case .submitted: return "SUBMITTED"
      case .provisioning: return "PROVISIONING"
      case .provisioned: return "PROVISIONED"
      case .validated: return "VALIDATED"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "DRAFT": self = .draft
      case "SUBMITTED": self = .submitted
      case "PROVISIONING": self = .provisioning
      case "PROVISIONED": self = .provisioned
      case "VALIDATED": self = .validated
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .draft
      case 2: self = .submitted
      case 3: self = .provisioning
      case 4: self = .provisioned
      case 5: self = .validated
      case 6: self = .cancelled
      case 7: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .draft: return try container.encode(1)
      case .submitted: return try container.encode(2)
      case .provisioning: return try container.encode(3)
      case .provisioned: return try container.encode(4)
      case .validated: return try container.encode(5)
      case .cancelled: return try container.encode(6)
      case .failed: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.ProvisioningConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
