// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A provisioning quota for a given project.
public struct ProvisioningQuota: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the provisioning quota.
  public var name: Swift.String = Swift.String()

  /// The asset type of this provisioning quota.
  public var assetType: ProvisioningQuota.AssetType = ProvisioningQuota.AssetType()

  /// The gcp service of the provisioning quota.
  public var gcpService: Swift.String = Swift.String()

  /// The specific location of the provisioining quota.
  public var location: Swift.String = Swift.String()

  /// The available count of the provisioning quota.
  public var availableCount: Swift.Int32 = Swift.Int32()

  /// The quota of one asset type.
  public var quota: OneOf_Quota? = nil

  /// Available quantity based on asset type.
  public var availability: OneOf_Availability? = nil

  /// Initialize a new instance of `ProvisioningQuota`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProvisioningQuota().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case assetType = "assetType"
    case gcpService = "gcpService"
    case location = "location"
    case availableCount = "availableCount"
    case instanceQuota = "instanceQuota"
    case serverCount = "serverCount"
    case networkBandwidth = "networkBandwidth"
    case storageGib = "storageGib"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.assetType = try container.decode(ProvisioningQuota.AssetType.self, forKey: .assetType)
    self.gcpService = try container.decode(Swift.String.self, forKey: .gcpService)
    self.location = try container.decode(Swift.String.self, forKey: .location)
    self.availableCount = try container.decode(Swift.Int32.self, forKey: .availableCount)

    var quota: OneOf_Quota? = nil
    let quotaCheckAndSet = {
      if quota != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'quota'"))
      }
      quota = $0
    }
    if let instanceQuota = try container.decodeIfPresent(
      InstanceQuota?.self, forKey: .instanceQuota)
    {
      try quotaCheckAndSet(.instanceQuota(instanceQuota))
    }
    self.quota = quota

    var availability: OneOf_Availability? = nil
    let availabilityCheckAndSet = {
      if availability != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'availability'"))
      }
      availability = $0
    }
    if let serverCount = try container.decodeIfPresent(Swift.Int64.self, forKey: .serverCount) {
      try availabilityCheckAndSet(.serverCount(serverCount))
    }
    if let networkBandwidth = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .networkBandwidth)
    {
      try availabilityCheckAndSet(.networkBandwidth(networkBandwidth))
    }
    if let storageGib = try container.decodeIfPresent(Swift.Int64.self, forKey: .storageGib) {
      try availabilityCheckAndSet(.storageGib(storageGib))
    }
    self.availability = availability
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.assetType, forKey: .assetType)
    try container.encode(self.gcpService, forKey: .gcpService)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.availableCount, forKey: .availableCount)

    if let choice = self.quota {
      switch choice {
      case .instanceQuota(let value):
        try container.encode(value, forKey: .instanceQuota)
      }
    }

    if let choice = self.availability {
      switch choice {
      case .serverCount(let value):
        try container.encode(value, forKey: .serverCount)
      case .networkBandwidth(let value):
        try container.encode(value, forKey: .networkBandwidth)
      case .storageGib(let value):
        try container.encode(value, forKey: .storageGib)
      }
    }
  }

  /// The available asset types for intake.
  public enum AssetType: Codable, Equatable, Sendable {
    /// The unspecified type.
    case unspecified
    /// The server asset type.
    case server
    /// The storage asset type.
    case storage
    /// The network asset type.
    case network
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .server: return 1
      case .storage: return 2
      case .network: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ASSET_TYPE_UNSPECIFIED"
      case .server: return "ASSET_TYPE_SERVER"
      case .storage: return "ASSET_TYPE_STORAGE"
      case .network: return "ASSET_TYPE_NETWORK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AssetType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ASSET_TYPE_UNSPECIFIED": self = .unspecified
      case "ASSET_TYPE_SERVER": self = .server
      case "ASSET_TYPE_STORAGE": self = .storage
      case "ASSET_TYPE_NETWORK": self = .network
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AssetType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .server
      case 2: self = .storage
      case 3: self = .network
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .server: return try container.encode(1)
      case .storage: return try container.encode(2)
      case .network: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The quota of one asset type.
  public enum OneOf_Quota: Codable, Equatable, Sendable {
    /// Instance quota.
    indirect case instanceQuota(InstanceQuota?)
  }

  /// Available quantity based on asset type.
  public enum OneOf_Availability: Codable, Equatable, Sendable {
    /// Server count.
    case serverCount(Swift.Int64)
    /// Network bandwidth, Gbps
    case networkBandwidth(Swift.Int64)
    /// Storage size (GB).
    case storageGib(Swift.Int64)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.ProvisioningQuota"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
