// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A storage volume.
public struct Volume: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this `Volume`.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// Format:
  /// `projects/{project}/locations/{location}/volumes/{volume}`
  public var name: Swift.String = Swift.String()

  /// An identifier for the `Volume`, generated by the backend.
  public var id: Swift.String = Swift.String()

  /// The storage type for this volume.
  public var storageType: Volume.StorageType = Volume.StorageType()

  /// The state of this storage volume.
  public var state: Volume.State = Volume.State()

  /// The requested size of this storage volume, in GiB.
  public var requestedSizeGib: Swift.Int64 = Swift.Int64()

  /// Originally requested size, in GiB.
  public var originallyRequestedSizeGib: Swift.Int64 = Swift.Int64()

  /// The current size of this storage volume, in GiB, including space reserved
  /// for snapshots. This size might be different than the requested size if the
  /// storage volume has been configured with auto grow or auto shrink.
  public var currentSizeGib: Swift.Int64 = Swift.Int64()

  /// Additional emergency size that was requested for this Volume, in GiB.
  /// current_size_gib includes this value.
  public var emergencySizeGib: Swift.Int64 = Swift.Int64()

  /// Maximum size volume can be expanded to in case of evergency, in GiB.
  public var maxSizeGib: Swift.Int64 = Swift.Int64()

  /// The size, in GiB, that this storage volume has expanded as a result of an
  /// auto grow policy. In the absence of auto-grow, the value is 0.
  public var autoGrownSizeGib: Swift.Int64 = Swift.Int64()

  /// The space remaining in the storage volume for new LUNs, in GiB, excluding
  /// space reserved for snapshots.
  public var remainingSpaceGib: Swift.Int64 = Swift.Int64()

  /// Details about snapshot space reservation and usage on the storage volume.
  public var snapshotReservationDetail: Volume.SnapshotReservationDetail? = nil

  /// The behavior to use when snapshot reserved space is full.
  public var snapshotAutoDeleteBehavior: Volume.SnapshotAutoDeleteBehavior =
    Volume.SnapshotAutoDeleteBehavior()

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Whether snapshots are enabled.
  public var snapshotEnabled: Swift.Bool = Swift.Bool()

  /// Immutable. Pod name.
  public var pod: Swift.String = Swift.String()

  /// Output only. Storage protocol for the Volume.
  public var `protocol`: Volume.Protocol_ = Volume.Protocol_()

  /// Output only. Whether this volume is a boot volume. A boot volume is one
  /// which contains a boot LUN.
  public var bootVolume: Swift.Bool = Swift.Bool()

  /// Immutable. Performance tier of the Volume.
  /// Default is SHARED.
  public var performanceTier: VolumePerformanceTier = VolumePerformanceTier()

  /// Input only. User-specified notes for new Volume.
  /// Used to provision Volumes that require manual intervention.
  public var notes: Swift.String = Swift.String()

  /// The workload profile for the volume.
  public var workloadProfile: Volume.WorkloadProfile = Volume.WorkloadProfile()

  /// Output only. Time after which volume will be fully deleted.
  /// It is filled only for volumes in COOLOFF state.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Instances this Volume is attached to.
  /// This field is set only in Get requests.
  public var instances: [Swift.String] = []

  /// Output only. Is the Volume attached at at least one instance.
  /// This field is a lightweight counterpart of `instances` field.
  /// It is filled in List responses as well.
  public var attached: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Volume`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Volume().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case id = "id"
    case storageType = "storageType"
    case state = "state"
    case requestedSizeGib = "requestedSizeGib"
    case originallyRequestedSizeGib = "originallyRequestedSizeGib"
    case currentSizeGib = "currentSizeGib"
    case emergencySizeGib = "emergencySizeGib"
    case maxSizeGib = "maxSizeGib"
    case autoGrownSizeGib = "autoGrownSizeGib"
    case remainingSpaceGib = "remainingSpaceGib"
    case snapshotReservationDetail = "snapshotReservationDetail"
    case snapshotAutoDeleteBehavior = "snapshotAutoDeleteBehavior"
    case labels = "labels"
    case snapshotEnabled = "snapshotEnabled"
    case pod = "pod"
    case `protocol` = "protocol"
    case bootVolume = "bootVolume"
    case performanceTier = "performanceTier"
    case notes = "notes"
    case workloadProfile = "workloadProfile"
    case expireTime = "expireTime"
    case instances = "instances"
    case attached = "attached"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.storageType = try container.decode(Volume.StorageType.self, forKey: .storageType)
    self.state = try container.decode(Volume.State.self, forKey: .state)
    self.requestedSizeGib = try container.decode(Swift.Int64.self, forKey: .requestedSizeGib)
    self.originallyRequestedSizeGib = try container.decode(
      Swift.Int64.self, forKey: .originallyRequestedSizeGib)
    self.currentSizeGib = try container.decode(Swift.Int64.self, forKey: .currentSizeGib)
    self.emergencySizeGib = try container.decode(Swift.Int64.self, forKey: .emergencySizeGib)
    self.maxSizeGib = try container.decode(Swift.Int64.self, forKey: .maxSizeGib)
    self.autoGrownSizeGib = try container.decode(Swift.Int64.self, forKey: .autoGrownSizeGib)
    self.remainingSpaceGib = try container.decode(Swift.Int64.self, forKey: .remainingSpaceGib)
    self.snapshotReservationDetail = try container.decodeIfPresent(
      Volume.SnapshotReservationDetail.self, forKey: .snapshotReservationDetail)
    self.snapshotAutoDeleteBehavior = try container.decode(
      Volume.SnapshotAutoDeleteBehavior.self, forKey: .snapshotAutoDeleteBehavior)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.snapshotEnabled = try container.decode(Swift.Bool.self, forKey: .snapshotEnabled)
    self.pod = try container.decode(Swift.String.self, forKey: .pod)
    self.`protocol` = try container.decode(Volume.Protocol_.self, forKey: .`protocol`)
    self.bootVolume = try container.decode(Swift.Bool.self, forKey: .bootVolume)
    self.performanceTier = try container.decode(
      VolumePerformanceTier.self, forKey: .performanceTier)
    self.notes = try container.decode(Swift.String.self, forKey: .notes)
    self.workloadProfile = try container.decode(
      Volume.WorkloadProfile.self, forKey: .workloadProfile)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .expireTime)
    self.instances = try container.decode([Swift.String].self, forKey: .instances)
    self.attached = try container.decode(Swift.Bool.self, forKey: .attached)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.storageType, forKey: .storageType)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.requestedSizeGib, forKey: .requestedSizeGib)
    try container.encode(self.originallyRequestedSizeGib, forKey: .originallyRequestedSizeGib)
    try container.encode(self.currentSizeGib, forKey: .currentSizeGib)
    try container.encode(self.emergencySizeGib, forKey: .emergencySizeGib)
    try container.encode(self.maxSizeGib, forKey: .maxSizeGib)
    try container.encode(self.autoGrownSizeGib, forKey: .autoGrownSizeGib)
    try container.encode(self.remainingSpaceGib, forKey: .remainingSpaceGib)
    try container.encode(self.snapshotReservationDetail, forKey: .snapshotReservationDetail)
    try container.encode(self.snapshotAutoDeleteBehavior, forKey: .snapshotAutoDeleteBehavior)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.snapshotEnabled, forKey: .snapshotEnabled)
    try container.encode(self.pod, forKey: .pod)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.bootVolume, forKey: .bootVolume)
    try container.encode(self.performanceTier, forKey: .performanceTier)
    try container.encode(self.notes, forKey: .notes)
    try container.encode(self.workloadProfile, forKey: .workloadProfile)
    try container.encode(self.expireTime, forKey: .expireTime)
    try container.encode(self.instances, forKey: .instances)
    try container.encode(self.attached, forKey: .attached)
  }

  /// Details about snapshot space reservation and usage on the storage volume.
  public struct SnapshotReservationDetail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The space on this storage volume reserved for snapshots, shown in GiB.
    public var reservedSpaceGib: Swift.Int64 = Swift.Int64()

    /// The percent of snapshot space on this storage volume actually being used
    /// by the snapshot copies. This value might be higher than 100% if the
    /// snapshot copies have overflowed into the data portion of the storage
    /// volume.
    public var reservedSpaceUsedPercent: Swift.Int32 = Swift.Int32()

    /// The amount, in GiB, of available space in this storage volume's reserved
    /// snapshot space.
    public var reservedSpaceRemainingGib: Swift.Int64 = Swift.Int64()

    /// Percent of the total Volume size reserved for snapshot copies.
    /// Enabling snapshots requires reserving 20% or more of
    /// the storage volume space for snapshots. Maximum reserved space for
    /// snapshots is 40%.
    /// Setting this field will effectively set snapshot_enabled to true.
    public var reservedSpacePercent: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `SnapshotReservationDetail`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SnapshotReservationDetail().with { $0.reservedSpaceGib = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.baremetalsolution.v2.Volume.SnapshotReservationDetail"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The storage type for a volume.
  public enum StorageType: Codable, Equatable, Sendable {
    /// The storage type for this volume is unknown.
    case unspecified
    /// The storage type for this volume is SSD.
    case ssd
    /// This storage type for this volume is HDD.
    case hdd
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ssd: return 1
      case .hdd: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STORAGE_TYPE_UNSPECIFIED"
      case .ssd: return "SSD"
      case .hdd: return "HDD"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STORAGE_TYPE_UNSPECIFIED": self = .unspecified
      case "SSD": self = .ssd
      case "HDD": self = .hdd
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ssd
      case 2: self = .hdd
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ssd: return try container.encode(1)
      case .hdd: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible states for a storage volume.
  public enum State: Codable, Equatable, Sendable {
    /// The storage volume is in an unknown state.
    case unspecified
    /// The storage volume is being created.
    case creating
    /// The storage volume is ready for use.
    case ready
    /// The storage volume has been requested to be deleted.
    case deleting
    /// The storage volume is being updated.
    case updating
    /// The storage volume is in cool off state. It will be deleted after
    /// `expire_time`.
    case coolOff
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .deleting: return 3
      case .updating: return 4
      case .coolOff: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .coolOff: return "COOL_OFF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "COOL_OFF": self = .coolOff
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .deleting
      case 4: self = .updating
      case 5: self = .coolOff
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .updating: return try container.encode(4)
      case .coolOff: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The kinds of auto delete behavior to use when snapshot reserved space is
  /// full.
  public enum SnapshotAutoDeleteBehavior: Codable, Equatable, Sendable {
    /// The unspecified behavior.
    case unspecified
    /// Don't delete any snapshots. This disables new snapshot creation, as
    /// long as the snapshot reserved space is full.
    case disabled
    /// Delete the oldest snapshots first.
    case oldestFirst
    /// Delete the newest snapshots first.
    case newestFirst
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .oldestFirst: return 2
      case .newestFirst: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SNAPSHOT_AUTO_DELETE_BEHAVIOR_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .oldestFirst: return "OLDEST_FIRST"
      case .newestFirst: return "NEWEST_FIRST"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SNAPSHOT_AUTO_DELETE_BEHAVIOR_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "OLDEST_FIRST": self = .oldestFirst
      case "NEWEST_FIRST": self = .newestFirst
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 2: self = .oldestFirst
      case 3: self = .newestFirst
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .disabled: return try container.encode(1)
      case .oldestFirst: return try container.encode(2)
      case .newestFirst: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Storage protocol.
  public enum Protocol_: Codable, Equatable, Sendable {
    /// Value is not specified.
    case unspecified
    /// Fibre Channel protocol.
    case fibreChannel
    /// NFS protocol means Volume is a NFS Share volume.
    /// Such volumes cannot be manipulated via Volumes API.
    case nfs
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fibreChannel: return 1
      case .nfs: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROTOCOL_UNSPECIFIED"
      case .fibreChannel: return "FIBRE_CHANNEL"
      case .nfs: return "NFS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROTOCOL_UNSPECIFIED": self = .unspecified
      case "FIBRE_CHANNEL": self = .fibreChannel
      case "NFS": self = .nfs
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fibreChannel
      case 2: self = .nfs
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .fibreChannel: return try container.encode(1)
      case .nfs: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible values for a workload profile.
  public enum WorkloadProfile: Codable, Equatable, Sendable {
    /// The workload profile is in an unknown state.
    case unspecified
    /// The workload profile is generic.
    case generic
    /// The workload profile is hana.
    case hana
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .generic: return 1
      case .hana: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WORKLOAD_PROFILE_UNSPECIFIED"
      case .generic: return "GENERIC"
      case .hana: return "HANA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WORKLOAD_PROFILE_UNSPECIFIED": self = .unspecified
      case "GENERIC": self = .generic
      case "HANA": self = .hana
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .generic
      case 2: self = .hana
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .generic: return try container.encode(1)
      case .hana: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.Volume"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
