// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration parameters for a new volume.
public struct VolumeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the volume config.
  public var name: Swift.String = Swift.String()

  /// A transient unique identifier to identify a volume within an
  /// ProvisioningConfig request.
  public var id: Swift.String = Swift.String()

  /// Whether snapshots should be enabled.
  public var snapshotsEnabled: Swift.Bool = Swift.Bool()

  /// The type of this Volume.
  public var type: VolumeConfig.Type_ = VolumeConfig.Type_()

  /// Volume protocol.
  public var `protocol`: VolumeConfig.Protocol_ = VolumeConfig.Protocol_()

  /// The requested size of this volume, in GB.
  public var sizeGb: Swift.Int32 = Swift.Int32()

  /// LUN ranges to be configured. Set only when protocol is PROTOCOL_FC.
  public var lunRanges: [VolumeConfig.LunRange] = []

  /// Machine ids connected to this volume. Set only when protocol is
  /// PROTOCOL_FC.
  public var machineIds: [Swift.String] = []

  /// NFS exports. Set only when protocol is PROTOCOL_NFS.
  public var nfsExports: [VolumeConfig.NfsExport] = []

  /// User note field, it can be used by customers to add additional information
  /// for the BMS Ops team .
  public var userNote: Swift.String = Swift.String()

  /// The GCP service of the storage volume. Available gcp_service are in
  /// https://cloud.google.com/bare-metal/docs/bms-planning.
  public var gcpService: Swift.String = Swift.String()

  /// Performance tier of the Volume.
  /// Default is SHARED.
  public var performanceTier: VolumePerformanceTier = VolumePerformanceTier()

  /// Initialize a new instance of `VolumeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VolumeConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case id = "id"
    case snapshotsEnabled = "snapshotsEnabled"
    case type = "type"
    case `protocol` = "protocol"
    case sizeGb = "sizeGb"
    case lunRanges = "lunRanges"
    case machineIds = "machineIds"
    case nfsExports = "nfsExports"
    case userNote = "userNote"
    case gcpService = "gcpService"
    case performanceTier = "performanceTier"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.snapshotsEnabled = try container.decode(Swift.Bool.self, forKey: .snapshotsEnabled)
    self.type = try container.decode(VolumeConfig.Type_.self, forKey: .type)
    self.`protocol` = try container.decode(VolumeConfig.Protocol_.self, forKey: .`protocol`)
    self.sizeGb = try container.decode(Swift.Int32.self, forKey: .sizeGb)
    self.lunRanges = try container.decode([VolumeConfig.LunRange].self, forKey: .lunRanges)
    self.machineIds = try container.decode([Swift.String].self, forKey: .machineIds)
    self.nfsExports = try container.decode([VolumeConfig.NfsExport].self, forKey: .nfsExports)
    self.userNote = try container.decode(Swift.String.self, forKey: .userNote)
    self.gcpService = try container.decode(Swift.String.self, forKey: .gcpService)
    self.performanceTier = try container.decode(
      VolumePerformanceTier.self, forKey: .performanceTier)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.snapshotsEnabled, forKey: .snapshotsEnabled)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.sizeGb, forKey: .sizeGb)
    try container.encode(self.lunRanges, forKey: .lunRanges)
    try container.encode(self.machineIds, forKey: .machineIds)
    try container.encode(self.nfsExports, forKey: .nfsExports)
    try container.encode(self.userNote, forKey: .userNote)
    try container.encode(self.gcpService, forKey: .gcpService)
    try container.encode(self.performanceTier, forKey: .performanceTier)
  }

  /// A LUN(Logical Unit Number) range.
  public struct LunRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Number of LUNs to create.
    public var quantity: Swift.Int32 = Swift.Int32()

    /// The requested size of each LUN, in GB.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `LunRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LunRange().with { $0.quantity = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VolumeConfig.LunRange"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A NFS export entry.
  public struct NfsExport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Network to use to publish the export.
    public var networkId: Swift.String = Swift.String()

    /// Export permissions.
    public var permissions: VolumeConfig.NfsExport.Permissions = VolumeConfig.NfsExport
      .Permissions()

    /// Disable root squashing, which is a feature of NFS.
    /// Root squash is a special mapping of the remote superuser (root) identity
    /// when using identity authentication.
    public var noRootSquash: Swift.Bool = Swift.Bool()

    /// Allow the setuid flag.
    public var allowSuid: Swift.Bool = Swift.Bool()

    /// Allow dev flag in NfsShare AllowedClientsRequest.
    public var allowDev: Swift.Bool = Swift.Bool()

    /// A client object.
    public var client: OneOf_Client? = nil

    /// Initialize a new instance of `NfsExport`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NfsExport().with { $0.networkId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case networkId = "networkId"
      case machineId = "machineId"
      case cidr = "cidr"
      case permissions = "permissions"
      case noRootSquash = "noRootSquash"
      case allowSuid = "allowSuid"
      case allowDev = "allowDev"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.networkId = try container.decode(Swift.String.self, forKey: .networkId)
      self.permissions = try container.decode(
        VolumeConfig.NfsExport.Permissions.self, forKey: .permissions)
      self.noRootSquash = try container.decode(Swift.Bool.self, forKey: .noRootSquash)
      self.allowSuid = try container.decode(Swift.Bool.self, forKey: .allowSuid)
      self.allowDev = try container.decode(Swift.Bool.self, forKey: .allowDev)

      var client: OneOf_Client? = nil
      let clientCheckAndSet = {
        if client != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'client'"))
        }
        client = $0
      }
      if let machineId = try container.decodeIfPresent(Swift.String.self, forKey: .machineId) {
        try clientCheckAndSet(.machineId(machineId))
      }
      if let cidr = try container.decodeIfPresent(Swift.String.self, forKey: .cidr) {
        try clientCheckAndSet(.cidr(cidr))
      }
      self.client = client
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.networkId, forKey: .networkId)
      try container.encode(self.permissions, forKey: .permissions)
      try container.encode(self.noRootSquash, forKey: .noRootSquash)
      try container.encode(self.allowSuid, forKey: .allowSuid)
      try container.encode(self.allowDev, forKey: .allowDev)

      if let choice = self.client {
        switch choice {
        case .machineId(let value):
          try container.encode(value, forKey: .machineId)
        case .cidr(let value):
          try container.encode(value, forKey: .cidr)
        }
      }
    }

    /// Permissions that can granted for an export.
    public enum Permissions: Codable, Equatable, Sendable {
      /// Unspecified value.
      case unspecified
      /// Read-only permission.
      case readOnly
      /// Read-write permission.
      case readWrite
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .readOnly: return 1
        case .readWrite: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PERMISSIONS_UNSPECIFIED"
        case .readOnly: return "READ_ONLY"
        case .readWrite: return "READ_WRITE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Permissions/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PERMISSIONS_UNSPECIFIED": self = .unspecified
        case "READ_ONLY": self = .readOnly
        case "READ_WRITE": self = .readWrite
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Permissions/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .readOnly
        case 2: self = .readWrite
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .readOnly: return try container.encode(1)
        case .readWrite: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// A client object.
    public enum OneOf_Client: Codable, Equatable, Sendable {
      /// Either a single machine, identified by an ID, or a comma-separated
      /// list of machine IDs.
      case machineId(Swift.String)
      /// A CIDR range.
      case cidr(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VolumeConfig.NfsExport"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The types of Volumes.
  public enum Type_: Codable, Equatable, Sendable {
    /// The unspecified type.
    case unspecified
    /// This Volume is on flash.
    case flash
    /// This Volume is on disk.
    case disk
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .flash: return 1
      case .disk: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .flash: return "FLASH"
      case .disk: return "DISK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "FLASH": self = .flash
      case "DISK": self = .disk
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .flash
      case 2: self = .disk
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .flash: return try container.encode(1)
      case .disk: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The protocol used to access the volume.
  public enum Protocol_: Codable, Equatable, Sendable {
    /// Unspecified value.
    case unspecified
    /// Fibre channel.
    case fc
    /// Network file system.
    case nfs
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fc: return 1
      case .nfs: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROTOCOL_UNSPECIFIED"
      case .fc: return "PROTOCOL_FC"
      case .nfs: return "PROTOCOL_NFS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Protocol_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROTOCOL_UNSPECIFIED": self = .unspecified
      case "PROTOCOL_FC": self = .fc
      case "PROTOCOL_NFS": self = .nfs
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Protocol_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fc
      case 2: self = .nfs
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .fc: return try container.encode(1)
      case .nfs: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.VolumeConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
