// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A snapshot of a volume. Only boot volumes can have snapshots.
public struct VolumeSnapshot: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the snapshot.
  public var name: Swift.String = Swift.String()

  /// Output only. An identifier for the snapshot, generated by the backend.
  public var id: Swift.String = Swift.String()

  /// The description of the snapshot.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation time of the snapshot.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The name of the volume which this snapshot belongs to.
  public var storageVolume: Swift.String = Swift.String()

  /// Output only. The type of the snapshot which indicates whether it was
  /// scheduled or manual/ad-hoc.
  public var type: VolumeSnapshot.SnapshotType = VolumeSnapshot.SnapshotType()

  /// Initialize a new instance of `VolumeSnapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VolumeSnapshot().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents the type of a snapshot.
  public enum SnapshotType: Codable, Equatable, Sendable {
    /// Type is not specified.
    case unspecified
    /// Snapshot was taken manually by user.
    case adHoc
    /// Snapshot was taken automatically as a part of a snapshot schedule.
    case scheduled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .adHoc: return 1
      case .scheduled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SNAPSHOT_TYPE_UNSPECIFIED"
      case .adHoc: return "AD_HOC"
      case .scheduled: return "SCHEDULED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SnapshotType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SNAPSHOT_TYPE_UNSPECIFIED": self = .unspecified
      case "AD_HOC": self = .adHoc
      case "SCHEDULED": self = .scheduled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SnapshotType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .adHoc
      case 2: self = .scheduled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .adHoc: return try container.encode(1)
      case .scheduled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.VolumeSnapshot"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
