// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A network VRF.
public struct VRF: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the VRF.
  public var name: Swift.String = Swift.String()

  /// The possible state of VRF.
  public var state: VRF.State = VRF.State()

  /// The QOS policy applied to this VRF.
  /// The value is only meaningful when all the vlan attachments have the same
  /// QoS. This field should not be used for new integrations, use vlan
  /// attachment level qos instead. The field is left for backward-compatibility.
  public var qosPolicy: VRF.QosPolicy? = nil

  /// The list of VLAN attachments for the VRF.
  public var vlanAttachments: [VRF.VlanAttachment] = []

  /// Initialize a new instance of `VRF`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VRF().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// QOS policy parameters.
  public struct QosPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The bandwidth permitted by the QOS policy, in gbps.
    public var bandwidthGbps: Swift.Double = Swift.Double()

    /// Initialize a new instance of `QosPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QosPolicy().with { $0.bandwidthGbps = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF.QosPolicy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// VLAN attachment details.
  public struct VlanAttachment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The peer vlan ID of the attachment.
    public var peerVlanId: Swift.Int64 = Swift.Int64()

    /// The peer IP of the attachment.
    public var peerIp: Swift.String = Swift.String()

    /// The router IP of the attachment.
    public var routerIp: Swift.String = Swift.String()

    /// Input only. Pairing key.
    public var pairingKey: Swift.String = Swift.String()

    /// The QOS policy applied to this VLAN attachment.
    /// This value should be preferred to using qos at vrf level.
    public var qosPolicy: VRF.QosPolicy? = nil

    /// Immutable. The identifier of the attachment within vrf.
    public var id: Swift.String = Swift.String()

    /// Optional. The name of the vlan attachment within vrf. This is of the form
    /// projects/{project_number}/regions/{region}/interconnectAttachments/{interconnect_attachment}
    public var interconnectAttachment: Swift.String = Swift.String()

    /// Initialize a new instance of `VlanAttachment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VlanAttachment().with { $0.peerVlanId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF.VlanAttachment"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible states for this VRF.
  public enum State: Codable, Equatable, Sendable {
    /// The unspecified state.
    case unspecified
    /// The vrf is provisioning.
    case provisioning
    /// The vrf is provisioned.
    case provisioned
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .provisioned: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .provisioned: return "PROVISIONED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "PROVISIONED": self = .provisioned
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .provisioned
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .provisioned: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
