// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A network VRF.
public struct VRF: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the VRF.
  public var name: Swift.String = Swift.String()

  /// The possible state of VRF.
  public var state: VRF.State = VRF.State()

  /// The QOS policy applied to this VRF.
  /// The value is only meaningful when all the vlan attachments have the same
  /// QoS. This field should not be used for new integrations, use vlan
  /// attachment level qos instead. The field is left for backward-compatibility.
  public var qosPolicy: VRF.QosPolicy? = nil

  /// The list of VLAN attachments for the VRF.
  public var vlanAttachments: [VRF.VlanAttachment] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VRF`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VRF().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let state = CodingKeys(stringValue: "state")
    static let qosPolicy = CodingKeys(stringValue: "qosPolicy")
    static let vlanAttachments = CodingKeys(stringValue: "vlanAttachments")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "state",
      "qosPolicy",
      "vlanAttachments",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(VRF.State.self, forKey: .state) {
      self.state = value
    }
    self.qosPolicy = try container.decodeIfPresent(VRF.QosPolicy.self, forKey: .qosPolicy)
    if let value = try container.decodeIfPresent(
      [VRF.VlanAttachment].self, forKey: .vlanAttachments)
    {
      self.vlanAttachments = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.qosPolicy, forKey: .qosPolicy)
    try container.encode(self.vlanAttachments, forKey: .vlanAttachments)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// QOS policy parameters.
  public struct QosPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The bandwidth permitted by the QOS policy, in gbps.
    public var bandwidthGbps: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QosPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QosPolicy().with { $0.bandwidthGbps = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let bandwidthGbps = CodingKeys(stringValue: "bandwidthGbps")

      static let _knownKeys: Set<Swift.String> = [
        "bandwidthGbps"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .bandwidthGbps) {
        self.bandwidthGbps = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.bandwidthGbps, forKey: .bandwidthGbps)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF.QosPolicy"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// VLAN attachment details.
  public struct VlanAttachment: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The peer vlan ID of the attachment.
    public var peerVlanId: Swift.Int64 = Swift.Int64()

    /// The peer IP of the attachment.
    public var peerIp: Swift.String = Swift.String()

    /// The router IP of the attachment.
    public var routerIp: Swift.String = Swift.String()

    /// Input only. Pairing key.
    public var pairingKey: Swift.String = Swift.String()

    /// The QOS policy applied to this VLAN attachment.
    /// This value should be preferred to using qos at vrf level.
    public var qosPolicy: VRF.QosPolicy? = nil

    /// Immutable. The identifier of the attachment within vrf.
    public var id: Swift.String = Swift.String()

    /// Optional. The name of the vlan attachment within vrf. This is of the form
    /// projects/{project_number}/regions/{region}/interconnectAttachments/{interconnect_attachment}
    public var interconnectAttachment: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VlanAttachment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VlanAttachment().with { $0.peerVlanId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let peerVlanId = CodingKeys(stringValue: "peerVlanId")
      static let peerIp = CodingKeys(stringValue: "peerIp")
      static let routerIp = CodingKeys(stringValue: "routerIp")
      static let pairingKey = CodingKeys(stringValue: "pairingKey")
      static let qosPolicy = CodingKeys(stringValue: "qosPolicy")
      static let id = CodingKeys(stringValue: "id")
      static let interconnectAttachment = CodingKeys(stringValue: "interconnectAttachment")

      static let _knownKeys: Set<Swift.String> = [
        "peerVlanId",
        "peerIp",
        "routerIp",
        "pairingKey",
        "qosPolicy",
        "id",
        "interconnectAttachment",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .peerVlanId) {
        self.peerVlanId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerIp) {
        self.peerIp = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .routerIp) {
        self.routerIp = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pairingKey) {
        self.pairingKey = value
      }
      self.qosPolicy = try container.decodeIfPresent(VRF.QosPolicy.self, forKey: .qosPolicy)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .interconnectAttachment)
      {
        self.interconnectAttachment = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.peerVlanId, forKey: .peerVlanId)
      try container.encode(self.peerIp, forKey: .peerIp)
      try container.encode(self.routerIp, forKey: .routerIp)
      try container.encode(self.pairingKey, forKey: .pairingKey)
      try container.encodeIfPresent(self.qosPolicy, forKey: .qosPolicy)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.interconnectAttachment, forKey: .interconnectAttachment)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF.VlanAttachment"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible states for this VRF.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The unspecified state.
    case unspecified
    /// The vrf is provisioning.
    case provisioning
    /// The vrf is provisioned.
    case provisioned
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .provisioned: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .provisioned: return "PROVISIONED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "PROVISIONED": self = .provisioned
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .provisioned
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .provisioned: return try container.encode("PROVISIONED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.baremetalsolution.v2.VRF"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
